/* Generated By:JavaCC: Do not edit this line. QueryParserConstants.java */
package fr.inserm.umr915.knime4ngs.nodes.sql.query;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface QueryParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ESCAPE_CHAR = 1;
  /** RegularExpression Id. */
  int SIMPLE_QUOTE_LITERAL = 2;
  /** RegularExpression Id. */
  int DOUBLE_QUOTE_LITERAL = 3;
  /** RegularExpression Id. */
  int COLUMN = 4;
  /** RegularExpression Id. */
  int ANY = 5;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<ESCAPE_CHAR>",
    "<SIMPLE_QUOTE_LITERAL>",
    "<DOUBLE_QUOTE_LITERAL>",
    "<COLUMN>",
    "<ANY>",
  };

}
