
package edu.washington.gs.evs.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DataQueryService", targetNamespace = "http://webservice.evs.gs.washington.edu/", wsdlLocation = "http://evs.gs.washington.edu/wsEVS/EVSDataQueryService?wsdl")
public class DataQueryService
    extends Service
{

    private final static URL DATAQUERYSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(edu.washington.gs.evs.webservice.DataQueryService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = edu.washington.gs.evs.webservice.DataQueryService.class.getResource(".");
            url = new URL(baseUrl, "http://evs.gs.washington.edu/wsEVS/EVSDataQueryService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://evs.gs.washington.edu/wsEVS/EVSDataQueryService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DATAQUERYSERVICE_WSDL_LOCATION = url;
    }

    public DataQueryService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DataQueryService() {
        super(DATAQUERYSERVICE_WSDL_LOCATION, new QName("http://webservice.evs.gs.washington.edu/", "DataQueryService"));
    }

    /**
     * 
     * @return
     *     returns DataQuery
     */
    @WebEndpoint(name = "DataQueryPort")
    public DataQuery getDataQueryPort() {
        return super.getPort(new QName("http://webservice.evs.gs.washington.edu/", "DataQueryPort"), DataQuery.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DataQuery
     */
    @WebEndpoint(name = "DataQueryPort")
    public DataQuery getDataQueryPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.evs.gs.washington.edu/", "DataQueryPort"), DataQuery.class, features);
    }

}
