/* Generated By:JavaCC: Do not edit this line. SelectSamplesParserConstants.java */
package fr.inserm.umr915.knime4ngs.nodes.vcf.selectsamples.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SelectSamplesParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LETTER = 5;
  /** RegularExpression Id. */
  int DIGIT = 6;
  /** RegularExpression Id. */
  int ESCAPE_CHAR = 7;
  /** RegularExpression Id. */
  int SIMPLE_QUOTE_LITERAL = 8;
  /** RegularExpression Id. */
  int DOUBLE_QUOTE_LITERAL = 9;
  /** RegularExpression Id. */
  int LPAR = 10;
  /** RegularExpression Id. */
  int RPAR = 11;
  /** RegularExpression Id. */
  int NOT = 12;
  /** RegularExpression Id. */
  int AND = 13;
  /** RegularExpression Id. */
  int OR = 14;
  /** RegularExpression Id. */
  int IDENTIFIER = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<LETTER>",
    "<DIGIT>",
    "<ESCAPE_CHAR>",
    "<SIMPLE_QUOTE_LITERAL>",
    "<DOUBLE_QUOTE_LITERAL>",
    "\"(\"",
    "\")\"",
    "<NOT>",
    "<AND>",
    "<OR>",
    "<IDENTIFIER>",
  };

}
