/* Generated By:JavaCC: Do not edit this line. SQLSchemaParserConstants.java */
package fr.inserm.umr915.knime4ngs.nodes.vcf.ucsc.generic;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SQLSchemaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DROP = 5;
  /** RegularExpression Id. */
  int CREATE = 6;
  /** RegularExpression Id. */
  int USE = 7;
  /** RegularExpression Id. */
  int TABLE = 8;
  /** RegularExpression Id. */
  int TEMPORARY = 9;
  /** RegularExpression Id. */
  int DATABASE = 10;
  /** RegularExpression Id. */
  int IF = 11;
  /** RegularExpression Id. */
  int ON = 12;
  /** RegularExpression Id. */
  int UPDATE = 13;
  /** RegularExpression Id. */
  int NOT = 14;
  /** RegularExpression Id. */
  int NULL = 15;
  /** RegularExpression Id. */
  int EXISTS = 16;
  /** RegularExpression Id. */
  int SET = 17;
  /** RegularExpression Id. */
  int ENUM = 18;
  /** RegularExpression Id. */
  int KEY = 19;
  /** RegularExpression Id. */
  int VARCHAR = 20;
  /** RegularExpression Id. */
  int CHAR = 21;
  /** RegularExpression Id. */
  int DEFAULTVALUE = 22;
  /** RegularExpression Id. */
  int CURRENT_TIMESTAMP = 23;
  /** RegularExpression Id. */
  int AUTO_INCREMENT = 24;
  /** RegularExpression Id. */
  int LONGBLOB = 25;
  /** RegularExpression Id. */
  int BLOB = 26;
  /** RegularExpression Id. */
  int BIGINT = 27;
  /** RegularExpression Id. */
  int INTEGER = 28;
  /** RegularExpression Id. */
  int SMALLINT = 29;
  /** RegularExpression Id. */
  int DATETIME = 30;
  /** RegularExpression Id. */
  int TIMESTAMP = 31;
  /** RegularExpression Id. */
  int DATE = 32;
  /** RegularExpression Id. */
  int DOUBLE = 33;
  /** RegularExpression Id. */
  int FLOAT = 34;
  /** RegularExpression Id. */
  int MEDIUMBLOG = 35;
  /** RegularExpression Id. */
  int TINYINT = 36;
  /** RegularExpression Id. */
  int TEXT = 37;
  /** RegularExpression Id. */
  int UNSIGNED = 38;
  /** RegularExpression Id. */
  int SIGNED = 39;
  /** RegularExpression Id. */
  int UNIQUE = 40;
  /** RegularExpression Id. */
  int PRIMARY = 41;
  /** RegularExpression Id. */
  int CHARACTER = 42;
  /** RegularExpression Id. */
  int COLLATE = 43;
  /** RegularExpression Id. */
  int LETTER = 44;
  /** RegularExpression Id. */
  int DIGIT = 45;
  /** RegularExpression Id. */
  int INT = 46;
  /** RegularExpression Id. */
  int IDENTIFIER1 = 47;
  /** RegularExpression Id. */
  int IDENTIFIER2 = 48;
  /** RegularExpression Id. */
  int VARIABLE = 49;
  /** RegularExpression Id. */
  int EQ = 50;
  /** RegularExpression Id. */
  int SEMICOLON = 51;
  /** RegularExpression Id. */
  int LPAR = 52;
  /** RegularExpression Id. */
  int RPAR = 53;
  /** RegularExpression Id. */
  int COMMA = 54;
  /** RegularExpression Id. */
  int ESCAPE_CHAR = 55;
  /** RegularExpression Id. */
  int SIMPLE_QUOTE_LITERAL = 56;
  /** RegularExpression Id. */
  int DOUBLE_QUOTE_LITERAL = 57;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "<token of kind 3>",
    "<token of kind 4>",
    "\"DROP\"",
    "\"CREATE\"",
    "\"USE\"",
    "\"TABLE\"",
    "\"TEMPORARY\"",
    "\"DATABASE\"",
    "\"IF\"",
    "\"ON\"",
    "\"UPDATE\"",
    "\"NOT\"",
    "\"NULL\"",
    "\"EXISTS\"",
    "<SET>",
    "<ENUM>",
    "\"KEY\"",
    "\"varchar\"",
    "\"char\"",
    "<DEFAULTVALUE>",
    "\"CURRENT_TIMESTAMP\"",
    "\"auto_increment\"",
    "\"longblob\"",
    "\"blob\"",
    "\"bigint\"",
    "\"int\"",
    "\"smallint\"",
    "\"datetime\"",
    "\"timestamp\"",
    "\"date\"",
    "\"double\"",
    "\"float\"",
    "\"mediumblob\"",
    "\"tinyint\"",
    "<TEXT>",
    "\"unsigned\"",
    "\"signed\"",
    "\"UNIQUE\"",
    "\"PRIMARY\"",
    "\"character\"",
    "\"collate\"",
    "<LETTER>",
    "<DIGIT>",
    "<INT>",
    "<IDENTIFIER1>",
    "<IDENTIFIER2>",
    "<VARIABLE>",
    "\"=\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "<ESCAPE_CHAR>",
    "<SIMPLE_QUOTE_LITERAL>",
    "<DOUBLE_QUOTE_LITERAL>",
  };

}
